# Generated by Django 3.1.7 on 2021-03-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2021)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.person')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.year')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.duty')),
            ],
            bases=('board.person',),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.person')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.year')),
            ],
            bases=('board.person',),
        ),
    ]
